### ISSUE TITLE
Could not connect to http://localhost:5002. Is the Cromwell server reachable?

### ISSUE THREAD

**Issue by tamadezhenshiyuncai** [stjudecloud/oliver#212]
i just configure as the cource or change the port， the same error:
Could not connect to http://localhost:5002. Is the Cromwell server reachable?
or Could not connect to http://localhost:8000. Is the Cromwell server reachable?

i don't know how to solve this problem,could you give me some advice,appreciate

**Comment by claymcleod** [comment]
Hi @tamadezhenshiyuncai,

Could you please tell me how you have Cromwell configured? What port do you have Cromwell running on? Further, can you try to curl the Cromwell server and see if you get a response back? `curl https://localhost:8000`, etc.
