### ISSUE TITLE
"cwl" & "cwl-workflow" in GitHub keywords

### ISSUE THREAD

**Issue by mr-c** [stjudecloud/oliver#267]
Hey-o,

To help guide new people in a good direction, can `cwl` and `cwl-workflow` be removed from the [keywords list for this repo](https://github.com/stjudecloud/oliver) as Cromwell has deprecated CWL for quite a while now?

![image](https://user-images.githubusercontent.com/1330696/220964614-12dc777e-c996-43ac-9fb3-ff940c724a14.png)

Thanks!

**Comment by adthrasher** [comment]
Removed. Thanks for the report!
