### ISSUE TITLE
Support submitting workflow over Cromwell server running behind gateway

### ISSUE THREAD

**Issue by Brico87** [stjudecloud/oliver#33]
Hi ! First, thanks for the amazing work here ! The Python code is so smooth and clean. A real pleasure to read into that !

Our issue now ;) We deploy Cromwell in Kubernetes so when we want to access it, we are going through an Istio gateway like "https://_our_host_/cromwell/" (no port is specified). This way to access Cromwell is different than with a local instance where you have "localhost:PORT".

Hence, we do not want for the "urljoin" method in the `api.py` to remove that "/cromwell" path. This should be linked to the fact that the Cromwell routes in the `api.py` module are specified as *absolute* route (like "/api/workflows/...").

A possible fix could be to specify only *relative* route in the `api.py` module and then to configure the "cromwell-api-server" with an url like "https://_our_host_/cromwell/" with a "/" at the end". Then it is working.

![image](https://user-images.githubusercontent.com/32193139/137098354-98d0247f-46e2-4418-8091-b12902b6f122.png)

```bash
[oliver] docker run -it oliver:latest --cromwell-server "https://_our_host_/cromwell/" --cromwell-api-version "v1" status --batch-interval-mins "2" --debug
[D 211013 08:13:49 api:56] GET api/workflows/{version}/query
[D 211013 08:13:49 api:58] Access url: https://_our_host_/cromwell/api/workflows/v1/query
[I 211013 08:13:49 workflows:156] Found 7 eligible workflows given search criteria.
[D 211013 ...
```

An alternative could be to not use the "urljoin" method but to do something a bit more complex with "urlparse" or just to add a "/" between the bae path and the Cromwell route.

What do you think ? Did you ever encountered that use case before ?

Cheers !

**Comment by ynedelec** [comment]
Hi !
Any news about this issue ?

Thanks !

**Comment by a-frantz** [comment]
Sorry about the delay, this fell off our radar. But give the newest release, `v1.4.4`, a try and let us know if it works.
