### ISSUE TITLE
`submit` args appear to be unused

### ISSUE THREAD

**Issue by claymcleod** [stjudecloud/oliver#6]
Did you have plans for these args Jobin?

https://github.com/stjudecloud/oliver/blob/a161cf6dd566c8a712436e817900fdca557932fb/oliver/subcommands/submit.py#L67-L68

**Comment by jsunny23** [comment]
@claymcleod I plan on removing them since the `memory` and `ncpu` requirements are set by workflows and one can add the workflow inputs to the oliver submit command. Does that make sense?

**Comment by claymcleod** [comment]
Makes sense to me!
