### ISSUE TITLE
Inline configuration parameters are not used with some commands

### ISSUE THREAD

**Issue by Melkaz** [stjudecloud/oliver#91]
Hello ! 

**Describe the bug**
Inline configuration parameters are not used when invoking some commands, such as `batches` or `status`
It seems to affect the `batch_interval_mins` parameter.

**To Reproduce**

Call:   
```bash
oliver \
  --cromwell-server https://aks-sciworkflow.sophiagenetics.com/cromwell/ \
  --cromwell-api-version v1 \
  --batch-interval-mins 2 \
  batches
```

Output:  
```
[E 220211 16:09:03 errors:28] The following required arguments are missing: batch_interval_mins!
We recommend you run 'oliver configure' to ensure all required arguments are cached in the oliver configuration file.
If you choose not to do this, you will need to pass their respective flags on the command line.
```
**Expected behavior**
Show job batches

Thanks for your help !

**Comment by claymcleod** [comment]
Hi @Melkaz, seems this issue has been resolved by the above PR. As such, I'm going to close the issue. Let us know if you have any problems with the latest version!
